# Generated by Django 4.2.16 on 2025-01-02 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_management.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=30, unique=True)),
                (
                    "username",
                    models.CharField(help_text="Ehsan", max_length=50, unique=True),
                ),
                (
                    "user_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_images/",
                        validators=[
                            user_management.models.validate_image_size,
                            user_management.models.validate_image_dimensions,
                        ],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="First Name", max_length=50, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Last Name", max_length=50, null=True
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("notofication_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_notifications",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
