# Generated by Django 4.2.16 on 2024-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="First Name", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, help_text="Last Name", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile Picture",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
