# Generated by Django 4.2.16 on 2025-01-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_images/"),
        ),
    ]
