# Generated by Django 4.2.17 on 2025-01-02 09:16

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[user_management.models.validate_image_size, user_management.models.validate_image_dimensions]),
        ),
    ]
