from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import FeatureRequestViewSet

app_name = 'platform_management'  # Set the app name for namespace in URLs

# Initialize the router for viewsets, which automatically handles URL routing for viewsets
router = DefaultRouter()
router.register(r'feature-requests', FeatureRequestViewSet)  # Registering the FeatureRequestViewSet to handle requests for 'feature-requests'

urlpatterns = [
    path('', include(router.urls)),  # Include all the URLs generated by the router
]
