# Generated by Django 4.2.16 on 2024-10-29 05:36

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionHistory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
