# Generated by Django 4.2.16 on 2024-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auditlog_delete_actionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.TextField(null=True),
        ),
    ]
