# Generated by Django 4.2.16 on 2025-01-10 14:02

from django.db import migrations, models
import django.db.models.deletion
import review_rating.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_select",
                    models.CharField(
                        choices=[
                            ("sexual", "SEXUAL"),
                            ("violence", "VIOLENCE"),
                            ("accusations", "ACCUSATIONS"),
                            ("terrorism", "TERRORISM"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "result_report",
                    models.CharField(
                        choices=[
                            ("ignore", "Ignore"),
                            ("Unchecked", "Unchecked"),
                            ("Remove", "Remove"),
                            ("UserBan", "User_Ban"),
                        ],
                        default=review_rating.models.ResultReport["Unchecked"],
                        max_length=256,
                    ),
                ),
                ("reason", models.TextField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Medium"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ],
                        default=3,
                    ),
                ),
                ("review_text", models.TextField()),
                ("hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_vote",
                        to="review_rating.review",
                    ),
                ),
            ],
        ),
    ]
