# Generated by Django 4.2.16 on 2024-10-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_rating', '0003_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='resson_select',
            new_name='reason_select',
        ),
    ]
