# Generated by Django 4.2.16 on 2024-11-09 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platform_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurerequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
