# Generated by Django 4.2.16 on 2024-11-25 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platform_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featurerequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
