# Generated by Django 4.2.16 on 2025-01-02 15:42

import business_management.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "business_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="business_images/",
                        validators=[
                            business_management.models.validate_image_size,
                            business_management.models.validate_image_dimensions,
                        ],
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("website_url", models.CharField(blank=True, max_length=50, null=True)),
                ("average_rank", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_name", models.CharField(max_length=256, unique=True)),
                (
                    "category_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="category_image/",
                        validators=[
                            business_management.models.validate_image_size,
                            business_management.models.validate_image_dimensions,
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("free", "FREE"), ("premium", "PREMIUM")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="business_management.business",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="business",
            name="business_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business_management.category",
            ),
        ),
    ]
