# Generated by Django 4.2.16 on 2025-01-23 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
