# Generated by Django 4.2.16 on 2025-01-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0003_subscription_business_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="business_image",
        ),
        migrations.AddField(
            model_name="business",
            name="business_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="business_images/"
            ),
        ),
    ]
