# Generated by Django 4.2.16 on 2024-11-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0003_alter_business_business_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="status",
        ),
    ]
