# Generated by Django 4.2.16 on 2025-01-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0004_remove_subscription_business_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(blank=True, null=True, upload_to="category_image/"),
        ),
    ]
