# Generated by Django 4.2.16 on 2024-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0005_category_business_business_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=256),
        ),
    ]
