# Generated by Django 4.2.17 on 2025-01-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0006_alter_business_business_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
