version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Bind your local code to the container /app directory
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DEBUG=True
      - DB_HOST=postgres # Ensure DB_HOST is set to 'postgres'
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=username
      - DB_PASSWORD=1234
    restart: always

volumes:
  postgres_data: