version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: ./Hengampilot/hengampilot  # Path to the backend directory
      dockerfile: dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Hengampilot/hengampilot:/app  # Bind backend source code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DEBUG=True
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=username
      - DB_PASSWORD=1234
    restart: always

  frontend:
    build:
      context: ./Hengampilot-front/frontend  # Path to the frontend directory
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"  # Map port 80 (NGINX) to port 3000 on host
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
